[tool.poetry]
name = "transkit"
version = "0.1.0"
description = ""
authors = ["Violet Nēšana <violet@nesana.org>"]

[tool.poetry.dependencies]
python = "3.8"
jupyterlab = "^2.1.5"
matplotlib = "^3.3.1"
scipy = "^1.5.1"
numpy = "^1.18.0"
pandas = "^1.0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
