#!/usr/bin/env python3

from injectio import pharma
import numpy as np
import pandas as pd
import random

random.seed()

date_fmt = "%Y.%b.%d.%H%M"
min_dose = 0.5
max_dose = 3.5

injs = pharma.rep_from(["2020.Feb.01.1200", 0.50, "ec"], n=61, freq='3D')
doses = 0.5*np.floor(np.linspace(min_dose-0.5, max_dose/0.5-0.5, num=len(injs))) + 0.5

print(f"# Automatically generated by `generate_injections.py` at {pd.Timestamp.now().strftime(date_fmt)}\n")
print("injections = [")
for i in range(len(injs)):
    inj = injs[i]
    dose = doses[i]
    dt = pd.to_timedelta(random.gauss(1.0, 120.0), unit='m')
    date = (inj[0] + dt).strftime(date_fmt)
    print(f'    ["{date}", {dose}, "{inj[2]}"],')
print("]")

print("""estradiol_measurements = [
    ["2020.Apr.22.1400", 85.0, "eclia"],
    ["2020.Jul.15.1330", 205.0, "eclia"],
]""")
